compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@monorepo-app-tony/monorepo@*":
    dependencies:
      eslint-plugin-import: "*"
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"

supportedArchitectures:
  cpu:
    - ia32
    - x86
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.0.1.cjs
