yarnPath: .yarn/releases/yarn-3.2.2.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

supportedArchitectures:
  cpu:
    - ia32
    - x86
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

packageExtensions:
  "eslint-config-react-app@*":
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"